### ISSUE TITLE
Change `master` to `main`

### ISSUE THREAD

**Issue by wyattoday** [hampusborgos/country-flags#106]
I'm thinking about changing the branch name "master" to "main". The word, "master" has a lot of racial baggage (especially the way it's used in computer science, i.e. usually paired with "slave"). It's an exclusionary term that has no particular redeeming features other than "that's the way it's always been done", which is a rather flaccid argument.

We're currently in the process of changing all of our internal git repositories from "master" to "main" and figured I might as well bring some of that effort to projects I have some influence in.

Once the change is made, anyone that has a local checkout just has to run the following commands to "switch over" to "main":

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

Tell me your thoughts, @hampusborgos .

**Comment by hampusborgos** [comment]
Sure! Why not. :)

**Comment by wyattoday** [comment]
I just realized I don't have access to editing the "master" branch. 🤦🏻‍♂️

Sorry to throw this at your feet, but do you mind editing it on the settings page (Settings tab, Branches, click the "edit icon", change to "main", click "Save changes").

Sorry, I would've communicated this privately if I had known I couldn't edit it on my own.

**Comment by hampusborgos** [comment]
I renamed it now.

**Comment by wyattoday** [comment]
Perfect, thanks!
