### ISSUE TITLE
Contribute back our version of the flag of Hong Kong

### ISSUE THREAD

**Issue by wyattoday** [hampusborgos/country-flags#110]
See commit https://github.com/hampusborgos/country-flags/commit/e0a8b0b1cb2bef7f36c8dc7a5600b6f0997b40ff

Update Flag of Hong Kong (use PRC colors as described in "[Specifications for the Regional Emblem of the Hong Kong Special Administrative Region of the People's Republic of China](https://www.elegislation.gov.hk/hk/A602)"):

> IV.
> 
> The chrominance value of the red colour of the regional emblem shall be identical with that of the national emblem of the People’s Republic of China.

Contribute back these changes here: https://commons.wikimedia.org/wiki/File:Flag_of_Hong_Kong.svg

**Comment by peepo5** [comment]
:+1:

**Comment by wyattoday** [comment]
Looks like someone contributed this change back.
