### ISSUE TITLE
Add united nation flag

### ISSUE THREAD

**Issue by likea-boss** [hampusborgos/country-flags#115]
Is it possible to add the UN flag from Wikipedia?

**Comment by wyattoday** [comment]
The problems are...

1. There's no ISO code for the U.N.
2. The U.N. is not a country or territory.
3. There are lots of organizations with flags. That doesn't mean the flags are noteworthy. (Though, the U.N. might be the sole exception to that).

At least item 1 must be solved before it would be added to this project.

**Comment by hampusborgos** [comment]
What would be the use case for this? There is no country picker where you can select the UN..?

**Comment by likea-boss** [comment]
It would be quite useful for using `country-flags` as emoji

**Comment by likea-boss** [comment]
> It would be quite useful for using `country-flags` as emoji

And in this case, other popular flags would be quite useful

**Comment by wyattoday** [comment]
Emojis already exist for that purpose.

**Comment by FerdyAnggaraRY** [comment]
Add Ascension's flag and Tristan da Cunha's flag, also edit it from St. Helena, Ascension & Tristan da Cunha

**Comment by wyattoday** [comment]
@FerdyAnggaraRY Please create a new issue.
