### ISSUE TITLE
Do you have an API or endpoint from which we can just get a country's image?

### ISSUE THREAD

**Issue by kash0296** [hampusborgos/country-flags#125]
I was previously using restcountries.eu for rendering flags on my website, but I'm looking to use something else, as their endpoint is no longer rendering flags for me. When i opened a flag in a new tab, i saw a cdn link. Can this link be used by users for rendering the flags? I would prefer not to install an extra npm module for this use case or store them in my codebase either locally. It would be great if we could use the CDN link!

Thanks!

**Comment by wyattoday** [comment]
Nope. Install it to your server. You can't rely on that 3rd party. They've broken in the past and will likely break in the future.

**Comment by kash0296** [comment]
Okay, thanks for clarifying!
