### ISSUE TITLE
Benelux (bx) Flag

### ISSUE THREAD

**Issue by dtlittle** [hampusborgos/country-flags#129]
Would it be possible to create a line item/flag for Benelux under the country code of "bx" ?

Site for reference: https://www.country-index.com/country_surveys.aspx?ID=11

**Comment by wyattoday** [comment]
There isn't an official flag for that economic treaty. Also, it's a bit like asking for a flag for [NAFTA](https://en.wikipedia.org/wiki/North_American_Free_Trade_Agreement).
