### ISSUE TITLE
Add sprite for all png images

### ISSUE THREAD

**Issue by drdim** [hampusborgos/country-flags#13]
generate sprite png for all images with css mapping.

**Comment by hjnilsson** [comment]
What resolution would be appropriate for such a mapping? 100x100?

**Comment by drdim** [comment]
I think create custom image size (from imagemin), default size one flag 1x - 20x14 px, 2x 40x28 px
or add npm build map command.

**Comment by Codefearingguy** [comment]
I think a sprite image is really necessary. 48 * 48 would be good

**Comment by AKlaus** [comment]
Google has their flags as 48x48 ([link](https://ssl.gstatic.com/i18n/flags/48x32/nobevel/40b411e8384b10c60bd78340cafbda86/flags.png)) and they show them as 24x24 images, so Retina displays handle the images gracefully.

Talking about sprites, I'd like to suggest an idea voiced [here on Stackoverflow.com](https://stackoverflow.com/a/11119265/968003) to save the flags in a grid according to the country ISO2 code, where 1st letter -> vertical position and 2nd letter -> horizontal position. So the flag location can be calculated with a very easy function on the client side without the need of 200+ extra style definitions.

**Comment by wyattoday** [comment]
There are lots of tools that take separate images and combines them to create a single sprite. Rather than re-create that work here, just use google to find one of the tools.

Here's one example: https://github.com/sprity/sprity
