### ISSUE TITLE
New Caledonian flag

### ISSUE THREAD

**Issue by TwoDoggo** [hampusborgos/country-flags#135]
New Caledonia is a French territory (one would argue not a country)  bearing the French national flag. In this instance rendering it relatively inconsequential and adding more issues when it comes to utilising this source (i.e. a Flag Quiz in which a user is unable to differ between French and New Caledonian Flag).

**Comment by hampusborgos** [comment]
This repository maps the flags for the countries defined by ISO-3166 and listed on iso.org: https://www.iso.org/obp/ui/#search

New Caledonia is part of this standard. If you would like to remove it, submit your complaint to the ISO standards board.

There are several more cases of territories sharing flag with the parent country. I would suggest making your own list of the countries included in your quiz separately instead, or just modifying the countries.json file and removing the territories you do not want listed, to be safe.
