### ISSUE TITLE
Extra colours in png files. Anti-aliased?

### ISSUE THREAD

**Issue by FMEEvangelist** [hampusborgos/country-flags#138]
If I inspect a four-colour flag (like ae.png) the png file contains 6 colours in its palette:

0	200,16,46
1	0,132,61
2	255,255,255
3	0,0,0
4	128,194,158
5	63,63,63

It should only be 4. Are the files being anti-aliased (if that's the term I mean)? It seems like there are lighter stripes in there. If colour is important then this kind of throws things off.

**Comment by wyattoday** [comment]
Yeah, likely antialiasing. Use the SVG if accuracy is important.
