### ISSUE TITLE
Latest package version does not include all changes from master branch

### ISSUE THREAD

**Issue by TaWReOn** [hampusborgos/country-flags#141]
Seems that latest package version tag (1.2.10) does not include changes from this commit > https://github.com/hampusborgos/country-flags/commit/d55d901689c8c180eb4bad34d859b764c1d3cc24.

**Comment by wyattoday** [comment]
Use the main branch.

Flags are ever-changing. And the SVG representations of flags are improving over time (to more closely match the intent of the region the flag represents).
