### ISSUE TITLE
Add Chinese Taipei flag

### ISSUE THREAD

**Issue by mar00nie** [hampusborgos/country-flags#147]
Could the Chinese Taipei flag be added, for use in sports?

ISO 3166 code is TPE

**Comment by wyattoday** [comment]
[Taiwan already has a country code (TW) and a flag attached.](https://github.com/hampusborgos/country-flags/blob/main/svg/tw.svg)

Individual provinces, states, cities, and other communities may have flags. That's beyond the scope of this project.

**Comment by mar00nie** [comment]
Taiwan is not allowed to use the TW flag for the Olympics and other sporting events, they are required to compete under "Chinese Taipei" and use the TPE flag instead.

**Comment by wyattoday** [comment]
If your particular use of flags requires pretending a country doesn’t exist (because a private committee is too chicken-shit to recognize Taiwan) then you can always include an exception in your app to include such-and-such flag
