### ISSUE TITLE
Optimize SVGs?

### ISSUE THREAD

**Issue by jpmckinney** [hampusborgos/country-flags#149]
A few SVGs are very large. Most are less than 10kB. Here are the largest 10:

```
 92K ht.svg
101K fk.svg
114K pe.svg
144K do.svg
156K mx.svg
173K ec.svg
186K af.svg
229K bo.svg
236K sv.svg
379K mp.svg
```

**Comment by jpmckinney** [comment]
Nevermind - users can do this with [svgo](https://github.com/svg/svgo) depending on what precision they need.

**Comment by wyattoday** [comment]
I would be wary of just running svgo blindly or in a batch manner without comparing the visual results of the input and output. SVGO tends to mangle things if not configured correctly.

I'm going through the project and updating flags and producing trimmer SVGs as I go.
