### ISSUE TITLE
new command to combine all the svgs into a single svg file

### ISSUE THREAD

**Issue by un33k** [hampusborgos/country-flags#35]
Angular menu loads each icon individually and if service worker is not enabled, that is one call per country to the backend.  It is so slow.

I am wondering if it is possible to do something like [mdi](https://materialdesignicons.com/), where they allow a single svg file for all the icons.

This way, there would be a single call to the backend to fetch all the flags.

Something like:

```
npm install -g svgexport imagemin-cli
npm run build-pngs -- 200 --combined=true:
```

**Comment by hjnilsson** [comment]
It is probably possible yes, you're thinking that each flag will be identified by an ID tag in a single SVG then?

**Comment by un33k** [comment]
@hjnilsson that is correct.

```typescript
// usage: if we had a single flags.svg
<mat-icon svgIcon="ca"></mat-icon>
<mat-icon svgIcon="us"></mat-icon>
```

Here you [see](https://github.com/neekware/nwx-mat/blob/master/pkgs/mat/src/mat.service.ts) how Angular material is used to register multiple flags svg(s) vs. a single icon svg (mdi.svg).

Sadly, one trip to the backend is required for each svg.

**Comment by wyattoday** [comment]
There are lots of tools that take separate images and combines them to create a single sprite. Rather than re-create that work here, just use google to find one of the tools.

Here's one example: https://github.com/svg-sprite/svg-sprite

**Comment by OzBob** [comment]
This package is used by Material! it's used a lot, it is impacting the internet by making millions of country flag requests per view.

Please reconsider adding a build step, to this repo, to create a single sprite for SVGs

**Comment by OzBob** [comment]
duplicate of https://github.com/hampusborgos/country-flags/issues/13

**Comment by OzBob** [comment]
partially completed in this PR - Anyone want to fix it? https://github.com/hampusborgos/country-flags/pull/122

**Comment by wyattoday** [comment]
@OzBob 

The code was broken (on Windows at the very least). Also, there's limited applicability for this code.

Rather than creating specialized scripts that will likely break (**_I'm_** not going to maintain it), just use generalized open source projects that already accomplish what you're looking for ([see above](https://github.com/hampusborgos/country-flags/issues/35#issuecomment-865857377))
