### ISSUE TITLE
Windows build-pngs never wires files to disk

### ISSUE THREAD

**Issue by JoueBien** [hampusborgos/country-flags#65]
**The behaviour**
 using 
```
npm run build-pngs -- :30
```
creates an empty folder with no images after converting SVG flags

**The expected behaviour**
folder is created and images are written to disk.

**Comment by pe2mbs** [comment]
Same on Linux Mint, after playing a-round i ended up with  
   # for file in *.svg; do svgexport $file "`basename $file svg`png" pad 50: ; done
 
This gave the error:
(node:31183) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 756035. Run "npm install" or "yarn install" to download a browser binary.
    at ChromeLauncher.launch (/usr/local/lib/node_modules/svgexport/node_modules/puppeteer/lib/Launcher.js:59:23)
(node:31183) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31183) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This error is not seen when running the script:
   # node scripts/build-pngs.js 50:

It just runs all the flag files from svg/ without reporting any error, just an empty output folder.

**Comment by wyattoday** [comment]
I don't use that script, but it looks like the error is telling you exactly what is wrong and how to fix it. Similarly, using google will give you more detailed solutions.
